import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin, Mountain, Route } from "lucide-react";
import InnerHero from "@/components/InnerHero";
import { getCmsData } from "@/lib/cms";
export const dynamic="force-dynamic";
const siteUrl="https://www.hoavienthienphucvinhhang.com.vn";
const title="Vị trí Thiên Phúc Vĩnh Hằng Viên | Uông Bí – Yên Tử, Quảng Ninh";
const description="Thông tin vị trí Công viên nghĩa trang Thiên Phúc Vĩnh Hằng Viên tại phường Uông Bí và phường Yên Tử, Quảng Ninh.";
export const metadata:Metadata={title,description,alternates:{canonical:"/vi-tri"},openGraph:{type:"website",locale:"vi_VN",url:`${siteUrl}/vi-tri`,siteName:"Thiên Phúc Vĩnh Hằng Viên",title,description}};
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase();
export default async function LocationPage(){const cms=await getCmsData();const album=cms.albums.find(a=>norm(a.title).includes("vi tri"));const photos=album?cms.photos.filter(p=>p.albumId===album.id):[];const hero=photos[0],gallery=photos.slice(1,9);return <main><InnerHero eyebrow="Vị trí dự án" title="Vị trí Thiên Phúc Vĩnh Hằng Viên" description="Dự án tọa lạc tại phường Uông Bí và phường Yên Tử, tỉnh Quảng Ninh – khu vực giàu giá trị văn hóa, cảnh quan và tâm linh."/><section className="section"><div className="shell location-grid"><div className="location-visual">{hero?<Image src={hero.url} alt="Vị trí Thiên Phúc Vĩnh Hằng Viên tại Uông Bí – Yên Tử, Quảng Ninh" fill priority sizes="(max-width:900px) 100vw,58vw" style={{objectFit:"cover"}}/>:<div style={{height:"100%",display:"grid",placeItems:"center",background:"#edf1ec"}}>Đang cập nhật hình ảnh vị trí</div>}<div className="location-badge"><MapPin size={24}/><span>Khu vực dự án</span><strong>Uông Bí – Yên Tử</strong></div></div><div className="location-copy"><span className="eyebrow">Kết nối khu vực</span><h2 className="section-title">Giữa không gian văn hóa – tâm linh Yên Tử</h2><p className="lead">Thiên Phúc Vĩnh Hằng Viên được triển khai trên địa bàn phường Uông Bí và phường Yên Tử, tỉnh Quảng Ninh.</p><p>Vị trí dự án gắn với cảnh quan vùng Yên Tử và mạng lưới giao thông của Uông Bí, tạo điều kiện thuận tiện cho gia đình trong quá trình thăm viếng và tưởng niệm.</p><div className="location-points"><div><Mountain size={18}/><span>Không gian cảnh quan gắn với vùng văn hóa Yên Tử</span></div><div><MapPin size={18}/><span>Địa bàn Uông Bí – Yên Tử, tỉnh Quảng Ninh</span></div><div><Route size={18}/><span>Kết nối với hệ thống giao thông khu vực</span></div></div><Link href="/lien-he" className="btn btn-outline">Nhận thông tin dự án <ArrowRight size={16}/></Link></div></div></section>{gallery.length>0&&<section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Hình ảnh vị trí</span><h2 className="section-title">Không gian khu vực dự án</h2><p className="lead max-copy">Hình ảnh được cập nhật trực tiếp từ album Vị trí của dự án.</p></div><div className="gallery-grid">{gallery.map((p,i)=><figure className={i===0?"gallery-wide":"gallery-item"} key={p.id}><Image src={p.url} alt={`Vị trí Thiên Phúc Vĩnh Hằng Viên ${i+2}`} fill sizes="(max-width:700px) 100vw,33vw" style={{objectFit:"cover"}}/></figure>)}</div></div></section>}</main>}
