import type { Metadata } from "next";
import Image from "next/image";
import InnerHero from "@/components/InnerHero";
import { Trees, Landmark, Car, HeartHandshake, Sparkles, ShieldCheck, Bus, Flower2 } from "lucide-react";
import {getCmsData} from "@/lib/cms";
export const dynamic="force-dynamic";
export const metadata: Metadata = { title: "Tiện ích & dịch vụ", description: "Hệ thống tiện ích và công trình kiến trúc tại Thiên Phúc Vĩnh Hằng Viên." };
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase();
const items=[[Landmark,"Nhà tang lễ","Không gian tổ chức nghi lễ trang nghiêm, thuận tiện cho gia đình."],[Sparkles,"Khu hỏa táng","Định hướng công nghệ hiện đại, vận hành đồng bộ với tổng thể dự án."],[ShieldCheck,"Khu lưu giữ tro cốt","Không gian lưu giữ trang trọng và an toàn."],[Trees,"Không gian tâm linh","Công trình tưởng niệm gắn với cảnh quan xanh và giá trị văn hóa Yên Tử."],[Flower2,"Không gian tưởng niệm","Khu vực dành cho hoạt động tưởng niệm và thăm viếng."],[Sparkles,"Hồ điều hòa","Góp phần tạo cảnh quan sinh thái và không gian thư thái."],[Bus,"Bãi đỗ xe","Tổ chức giao thông nội khu thuận tiện cho khách thăm viếng."],[HeartHandshake,"Khu dịch vụ","Hỗ trợ gia đình trong quá trình tư vấn, nghi lễ và chăm sóc."],[Car,"Giao thông nội khu","Hệ thống đường nội bộ kết nối các phân khu chức năng."]];
export default async function AmenityPage(){const cms=await getCmsData();const album=cms.albums.find(a=>norm(a.title).includes("cong trinh kien truc"));const photos=album?cms.photos.filter(p=>p.albumId===album.id):[];return <main><InnerHero eyebrow="Hệ tiện ích đồng bộ" title="Tiện ích & dịch vụ" description="Hệ thống công trình và dịch vụ được tổ chức để tạo nên một không gian tưởng niệm trang nghiêm, thuận tiện và hài hòa cùng thiên nhiên."/>{photos[0]&&<section className="section"><div className="shell two"><div><span className="eyebrow">Không gian kiến trúc</span><h2 className="section-title">Công trình hòa vào cảnh quan xanh</h2><p className="lead">Kiến trúc trong dự án được định hướng kết nối với cảnh quan, không gian tâm linh và hệ thống dịch vụ, tạo nên trải nghiệm trang trọng nhưng gần gũi với thiên nhiên.</p></div><div style={{position:"relative",minHeight:360,borderRadius:20,overflow:"hidden"}}><Image src={photos[0].url} alt="Công trình tiện ích Thiên Phúc Vĩnh Hằng Viên" fill sizes="50vw" style={{objectFit:"cover"}}/></div></div></section>}<section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Công trình & dịch vụ</span><h2 className="section-title">Đồng bộ trong từng trải nghiệm</h2><p className="lead max-copy">Các tiện ích được định hướng liên kết chặt chẽ với cảnh quan, giao thông nội khu và các khu an táng, giúp hành trình thăm viếng của gia đình nhẹ nhàng và thuận tiện hơn.</p></div><div className="amenities">{items.map(([Icon,title,desc]:any)=><article className="amenity" key={title}><Icon size={26}/><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>{photos.length>1&&<section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Hình ảnh dự án</span><h2 className="section-title">Công trình kiến trúc & tiện ích</h2></div><div className="gallery-grid">{photos.slice(1,9).map((p,i)=><figure key={p.id} className="gallery-item"><Image src={p.url} alt={`Tiện ích Thiên Phúc Vĩnh Hằng Viên ${i+2}`} fill sizes="25vw" style={{objectFit:"cover"}}/></figure>)}</div></div></section>}</main>}
