import type { Metadata } from "next";
import Image from "next/image";
import InnerHero from "@/components/InnerHero";
import { getCmsData } from "@/lib/cms";

export const dynamic="force-dynamic";
export const metadata: Metadata={title:"Tiến độ",description:"Cập nhật tiến độ dự án Thiên Phúc Vĩnh Hằng Viên từ khởi động đến kế hoạch hoàn thành."};
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase();
export default async function ProgressPage(){const cms=await getCmsData();const album=cms.albums.find(a=>norm(a.title).includes("tien do thi cong"));const photos=album?cms.photos.filter(p=>p.albumId===album.id):[];return <main><InnerHero eyebrow="Cập nhật dự án" title="Tiến độ Thiên Phúc Vĩnh Hằng Viên" description="Theo dõi các mốc triển khai chính của dự án và hình ảnh thi công thực tế khi được cập nhật trong hệ thống quản trị."/><section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Lộ trình triển khai</span><h2 className="section-title">Từ khởi động đến hoàn thiện</h2><p className="lead max-copy">Dự án khởi động ngày 02/06/2026 và dự kiến hoàn thành trong Quý II/2028. Nội dung dưới đây thể hiện các mốc thông tin đã được công bố và sẽ được bổ sung khi có cập nhật mới.</p></div><div className="detail-cards"><article className="detail-card"><span>01</span><h3>02/06/2026</h3><p>Khởi động Dự án Công viên nghĩa trang Thiên Phúc Vĩnh Hằng Viên tại Quảng Ninh.</p></article><article className="detail-card"><span>02</span><h3>Giai đoạn triển khai</h3><p>Thực hiện các hạng mục hạ tầng, cảnh quan và công trình theo kế hoạch dự án.</p></article><article className="detail-card"><span>03</span><h3>Quý II/2028</h3><p>Mốc dự kiến hoàn thành dự án theo thông tin công bố hiện tại.</p></article></div></div></section>{photos.length>0&&<section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Hình ảnh thực tế</span><h2 className="section-title">Tiến độ thi công</h2></div><div className="gallery-grid">{photos.slice(0,6).map((p,i)=><figure key={p.id} className={i===0?"gallery-wide":""}><Image src={p.url} alt={`Tiến độ thi công Thiên Phúc Vĩnh Hằng Viên ${i+1}`} fill sizes="(max-width:700px) 100vw,33vw" quality={68} style={{objectFit:"cover"}}/></figure>)}</div></div></section>}</main>}
