import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bus, CalendarDays, Car, Coins, Flower2, HeartHandshake, Landmark, MapPin, Mountain, ShieldCheck, Sparkles, TreePine } from "lucide-react";
import { getCmsData, type CmsPhoto } from "@/lib/cms";

export const dynamic="force-dynamic";
const siteUrl="https://hoavienthienphucvinhhang.com.vn";
const seoTitle="Thiên Phúc Vĩnh Hằng Viên | Công viên nghĩa trang Uông Bí – Yên Tử";
const seoDescription="Thiên Phúc Vĩnh Hằng Viên là dự án công viên nghĩa trang sinh thái tại Uông Bí – Yên Tử, Quảng Ninh, quy mô 32,54 ha, không gian an nghỉ thanh tịnh, nhân văn và bền vững.";
export const metadata:Metadata={title:seoTitle,description:seoDescription,keywords:["Thiên Phúc Vĩnh Hằng Viên","công viên nghĩa trang Thiên Phúc","nghĩa trang Uông Bí","nghĩa trang Yên Tử","công viên nghĩa trang Quảng Ninh","mộ phần Quảng Ninh"],alternates:{canonical:"/"},robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},openGraph:{type:"website",locale:"vi_VN",url:siteUrl,siteName:"Thiên Phúc Vĩnh Hằng Viên",title:seoTitle,description:seoDescription},twitter:{card:"summary_large_image",title:seoTitle,description:seoDescription}};
const fallback={hero:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=68",location:"https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1200&q=65"};
const values=[[TreePine,"CÔNG VIÊN SINH THÁI","Cảnh quan xanh hài hòa, bền vững"],[Landmark,"GIÁ TRỊ TÂM LINH","Gắn kết với văn hóa Yên Tử – Trúc Lâm"],[HeartHandshake,"NHÂN VĂN BỀN VỮNG","Không gian an nghỉ trang nghiêm, yên bình"],[ShieldCheck,"DỊCH VỤ CHU TOÀN","Đồng hành trọn đời cùng gia đình"]];
const amenities=[[Landmark,"NHÀ TANG LỄ","Trang nghiêm, hiện đại"],[Mountain,"KHU HÓA TÁNG","Công nghệ hiện đại"],[ShieldCheck,"KHU LƯU GIỮ TRO CỐT","An toàn, trang trọng"],[TreePine,"NHÀ NGUYỆN","Không gian thanh tịnh"],[Flower2,"KHÔNG GIAN TƯỞNG NIỆM","Tôn vinh ký ức"],[Sparkles,"HỒ ĐIỀU HÒA","Cảnh quan sinh thái"],[Bus,"BÃI ĐỖ XE","Rộng rãi, thuận tiện"],[HeartHandshake,"KHU DỊCH VỤ","Chu toàn nhu cầu"]];
const schema={"@context":"https://schema.org","@graph":[{"@type":"WebSite",url:siteUrl,name:"Thiên Phúc Vĩnh Hằng Viên",inLanguage:"vi-VN",description:seoDescription},{"@type":"Place",name:"Công viên nghĩa trang Thiên Phúc Vĩnh Hằng Viên",url:siteUrl,address:{"@type":"PostalAddress",addressLocality:"Uông Bí – Yên Tử",addressRegion:"Quảng Ninh",addressCountry:"VN"}}]};

export default async function Home(){
 const cms=await getCmsData();
 const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase().trim();
 const fromAlbum=(...names:string[])=>{const keys=names.map(norm);const a=cms.albums.find(x=>keys.some(k=>norm(x.title)===k||norm(x.title).includes(k)));return a?cms.photos.filter(p=>p.albumId===a.id):[]};
 const logos=fromAlbum("logo");
 const overview=fromAlbum("toàn cảnh","toàn cảnh dự án");
 const location=fromAlbum("vị trí");
 const planning=fromAlbum("mặt bằng tổng thể");
 const productsAlbum=fromAlbum("mẫu mộ");
 const architecture=fromAlbum("công trình kiến trúc");
 const progress=fromAlbum("tiến độ thi công");
 const usable=cms.photos.filter(p=>!logos.some(l=>l.id===p.id));
 const pick=(arr:CmsPhoto[],i=0,fb=fallback.hero)=>arr[i]?.url||arr[0]?.url||fb;
 const hero=pick(overview,0,pick(planning,0,fallback.hero));
 const locationImage=pick(location,0,fallback.location);
 const productImages=[0,1,2].map(i=>pick(productsAlbum,i,hero));
 const progressImages=[0,1,2,3].map(i=>pick(progress,i,hero));
 const architectureImage=pick(architecture,0,hero);
 const gallery=[...overview,...planning,...architecture].filter((p,i,a)=>a.findIndex(x=>x.url===p.url)===i).slice(0,8);
 const newsImages=[...progress,...overview,...usable].filter((p,i,a)=>a.findIndex(x=>x.url===p.url)===i).slice(0,4);
 const published=cms.posts.filter(p=>p.status==="Đã xuất bản").slice(0,4);
 const productCards=[["MỘ ĐƠN","Thiết kế trang trọng, hài hòa với thiên nhiên",productImages[0]],["MỘ ĐÔI","Gắn kết yêu thương – Bên nhau vĩnh hằng",productImages[1]],["MỘ GIA TỘC","Không gian tôn nghiêm cho các thế hệ",productImages[2]]];
 return <main className="ref-home">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
 <section className="ref-hero"><Image className="ref-hero-bg" src={hero} alt="Toàn cảnh Thiên Phúc Vĩnh Hằng Viên Uông Bí Yên Tử Quảng Ninh" fill priority fetchPriority="high" sizes="100vw" quality={70}/><div className="ref-hero-overlay"/><div className="shell ref-hero-copy"><h1>{cms.home.heroTitle}</h1><h3>Kiến tạo không gian an nghỉ</h3><h2>{cms.home.heroSubtitle}</h2><p>{cms.home.heroDescription}</p><div className="ref-actions"><Link href="/gioi-thieu" className="ref-btn green">KHÁM PHÁ DỰ ÁN</Link><Link href="/lien-he" className="ref-btn white"><CalendarDays size={16}/> ĐĂNG KÝ THAM QUAN</Link></div></div></section>
 <section className="shell ref-facts"><div><MapPin/><p><b>32,54 ha</b><span>QUY MÔ DỰ ÁN</span></p></div><div><Coins/><p><b>~451 tỷ đồng</b><span>TỔNG MỨC ĐẦU TƯ</span></p></div><div><CalendarDays/><p><b>02/06/2026</b><span>KHỞI ĐỘNG DỰ ÁN</span></p></div><div><Sparkles/><p><b>Quý II/2028</b><span>DỰ KIẾN HOÀN THÀNH</span></p></div></section>
 <section className="ref-overview"><div className="shell ref-overview-grid"><div className="ref-overview-copy"><span className="ref-ornament">♧</span><h2>TỔNG QUAN DỰ ÁN</h2><p>Thiên Phúc Vĩnh Hằng Viên là công viên nghĩa trang sinh thái hiện đại tại Uông Bí – Yên Tử, Quảng Ninh, kết hợp hài hòa giữa giá trị truyền thống, kiến trúc tâm linh và cảnh quan thiên nhiên.</p><Link className="ref-btn green" href="/gioi-thieu">TÌM HIỂU THÊM</Link></div><div className="ref-values">{values.map(([Icon,t,d]:any)=><article key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="ref-location"><div className="ref-location-image"><Image src={locationImage} alt="Vị trí Thiên Phúc Vĩnh Hằng Viên tại Uông Bí Yên Tử Quảng Ninh" fill sizes="(max-width:900px) 100vw,50vw" quality={66}/></div><div className="ref-location-copy"><h2>VỊ TRÍ & KẾT NỐI</h2><p>Dự án tọa lạc tại phường Uông Bí và phường Yên Tử, tỉnh Quảng Ninh – vùng đất linh thiêng, giàu truyền thống văn hóa và tâm linh.</p><div className="ref-distance"><div><Mountain/><b>Yên Tử</b><span>Kết nối vùng di sản</span></div><div><MapPin/><b>Uông Bí</b><span>Kết nối trung tâm</span></div><div><Car/><b>Quảng Ninh</b><span>Giao thông thuận tiện</span></div></div><Link className="ref-btn white outline" href="/vi-tri">XEM CHI TIẾT VỊ TRÍ <ArrowRight size={14}/></Link></div></section>
 <section className="ref-section"><div className="shell"><div className="ref-title"><h2>SẢN PHẨM AN TÁNG</h2><p>Hình ảnh trực tiếp từ album Mẫu mộ</p></div><div className="ref-products">{productCards.map(([n,d,img])=><article key={n}><div className="ref-card-image"><Image src={img} alt={`${n} Thiên Phúc Vĩnh Hằng Viên`} fill sizes="(max-width:600px) 100vw,(max-width:900px) 50vw,33vw" quality={64}/></div><div><Flower2/><h3>{n}</h3><p>{d}</p><Link href="/san-pham">Xem chi tiết <ArrowRight size={12}/></Link></div></article>)}</div></div></section>
 <section className="ref-amenity"><div className="shell"><div className="ref-title"><h2>TIỆN ÍCH & CÔNG TRÌNH KIẾN TRÚC</h2><p>Hình ảnh trực tiếp từ album Công trình kiến trúc</p></div>{architecture.length>0&&<div className="home-architecture"><Image src={architectureImage} alt="Công trình kiến trúc Thiên Phúc Vĩnh Hằng Viên" fill sizes="100vw" quality={62}/></div>}<div className="ref-amenity-grid">{amenities.map(([Icon,n,d]:any)=><article key={n}><Icon/><h3>{n}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="ref-progress"><div className="shell ref-progress-grid"><div><span>♧</span><h2>TIẾN ĐỘ DỰ ÁN</h2><p>Hình ảnh cập nhật trực tiếp từ album Tiến độ thi công.</p><Link href="/tien-do" className="ref-btn gold-outline">XEM TIẾN ĐỘ</Link></div><div className="ref-progress-cards">{["Chuẩn bị & San nền","Thi công hạ tầng","Thi công công trình","Hoàn thiện cảnh quan"].map((x,i)=><article key={x}><div className="ref-progress-image"><Image src={progressImages[i]} alt={`${x} Thiên Phúc Vĩnh Hằng Viên`} fill sizes="(max-width:900px) 50vw,20vw" quality={60}/></div><p>{x}</p></article>)}</div></div></section>
 {gallery.length>0&&<section className="ref-section cms-gallery"><div className="shell"><div className="ref-title"><h2>HÌNH ẢNH DỰ ÁN</h2><p>Toàn cảnh, mặt bằng tổng thể và công trình kiến trúc của dự án.</p></div><div className="cms-gallery-grid">{gallery.map((p,i)=><figure key={p.id}><Image src={p.url} alt={`Hình ảnh Thiên Phúc Vĩnh Hằng Viên ${i+1}`} fill sizes="(max-width:600px) 50vw,25vw" quality={58}/></figure>)}</div><div className="cms-gallery-action"><Link className="ref-btn green" href="/thu-vien">XEM TOÀN BỘ ALBUM</Link></div></div></section>}
 <section className="ref-section ref-news"><div className="shell"><div className="ref-news-head"><h2>TIN TỨC</h2><Link href="/tin-tuc">XEM TẤT CẢ ›</Link></div><div className="ref-news-grid">{(published.length?published:[{id:"fallback",date:"02/06/2026",title:"Khởi động dự án Công viên nghĩa trang Thiên Phúc Vĩnh Hằng Viên",status:"Đã xuất bản" as const}]).map((post,i)=><article key={post.id}><div className="ref-news-image"><Image src={newsImages[i%Math.max(newsImages.length,1)]?.url||hero} alt={post.title} fill sizes="(max-width:600px) 100vw,(max-width:900px) 50vw,25vw" quality={58}/></div><div><small>{post.date}</small><h3>{post.title}</h3><Link href="/tin-tuc">Xem chi tiết <ArrowRight size={12}/></Link></div></article>)}</div></div></section>
 <section className="ref-register"><div className="ref-register-bg"><Image src={pick(planning,0,hero)} alt="Mặt bằng tổng thể Thiên Phúc Vĩnh Hằng Viên" fill sizes="100vw" quality={50}/></div><div className="ref-register-overlay"/><div className="shell ref-register-content"><div className="ref-title"><h2>ĐĂNG KÝ THAM QUAN & TƯ VẤN</h2><p>Đội ngũ chuyên viên sẵn sàng hỗ trợ Quý khách qua hotline {cms.home.hotline}.</p></div><div className="ref-register-box"><input placeholder="Họ và tên*"/><input placeholder="Số điện thoại*"/><select defaultValue=""><option value="" disabled>Nhu cầu quan tâm</option><option>Sản phẩm an táng</option><option>Tham quan dự án</option><option>Tư vấn thông tin</option></select><Link href="/lien-he" className="ref-btn green">ĐĂNG KÝ NGAY</Link></div></div></section>
 </main>
}
