import Link from "next/link";
import { ArrowRight, Leaf, MapPin, ShieldCheck, Sparkles, TreePine } from "lucide-react";

const products=[
  ["Không gian đơn","Thiết kế chỉn chu, riêng tư và hài hòa cùng cảnh quan.","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=80"],
  ["Không gian song thân","Một nơi an yên để gìn giữ sự gắn kết và ký ức gia đình.","https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1000&q=80"],
  ["Khuôn viên gia tộc","Không gian riêng trang trọng dành cho nhiều thế hệ.","https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1000&q=80"]
];
const amenities=[[TreePine,"Cảnh quan sinh thái","Không gian xanh được tổ chức hài hòa, tạo cảm giác thanh tịnh."],[Sparkles,"Không gian tưởng niệm","Kiến trúc trang trọng, đề cao giá trị tinh thần và ký ức."],[MapPin,"Kết nối thuận tiện","Trải nghiệm tiếp cận được định hướng rõ ràng, thuận tiện cho gia đình."],[ShieldCheck,"Chăm sóc chu toàn","Dịch vụ được xây dựng theo tinh thần tận tâm và bền vững."],[Leaf,"Vườn hoa & cây xanh","Cảnh quan theo mùa, cân bằng thiên nhiên và kiến trúc."],[Sparkles,"Dịch vụ gia đình","Hỗ trợ tư vấn, thăm viếng và các nhu cầu tưởng niệm."]];

export default function Home(){return <main>
<section className="hero"><div className="shell"><div className="hero-copy"><span className="eyebrow">Không gian an yên · Giá trị trường tồn</span><h1>CAO<br/>THANH TÂM</h1><p>Một không gian được kiến tạo với tinh thần thanh tịnh, trang trọng và nhân văn — nơi ký ức được gìn giữ giữa thiên nhiên.</p><div className="actions"><Link className="btn btn-gold" href="/gioi-thieu">Khám phá <ArrowRight size={15}/></Link><Link className="btn btn-light" href="/lien-he">Đăng ký tham quan</Link></div></div></div></section>
<section className="stats"><div className="shell stats-grid"><div className="stat"><b>01</b><span>Không gian quy hoạch đồng bộ</span></div><div className="stat"><b>02</b><span>Cảnh quan xanh & thanh tịnh</span></div><div className="stat"><b>03</b><span>Dịch vụ chăm sóc chu toàn</span></div><div className="stat"><b>04</b><span>Giá trị bền vững cho gia đình</span></div></div></section>
<section className="section"><div className="shell two"><div><span className="eyebrow">Cao Thanh Tâm</span><h2 className="section-title">Một miền an tĩnh giữa thiên nhiên</h2><p className="lead">Cao Thanh Tâm hướng tới một trải nghiệm khác biệt: cảnh quan tinh tế, kiến trúc tiết chế và dịch vụ tận tâm. Mỗi không gian được chăm chút để trở thành nơi tưởng niệm trang trọng, gần gũi và bình yên cho nhiều thế hệ.</p><div className="actions"><Link className="btn btn-gold" href="/gioi-thieu">Tìm hiểu thêm <ArrowRight size={15}/></Link></div></div><img className="media" src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85" alt="Cảnh quan xanh Cao Thanh Tâm"/></div></section>
<section className="section dark"><div className="shell"><span className="eyebrow">Không gian lựa chọn</span><h2 className="section-title">Gìn giữ ký ức<br/>qua nhiều thế hệ</h2><div className="products">{products.map(([name,desc,img])=><article className="product" key={name}><img src={img} alt={name}/><div className="product-copy"><h3>{name}</h3><p>{desc}</p><Link href="/san-pham">Xem chi tiết →</Link></div></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="two"><div><span className="eyebrow">Tiện ích & dịch vụ</span><h2 className="section-title">Chu toàn trong từng trải nghiệm</h2></div><p className="lead">Từ cảnh quan đến dịch vụ, hệ thống tiện ích được định hướng để gia đình có một hành trình thăm viếng nhẹ nhàng, thuận tiện và trang trọng.</p></div><div className="amenities">{amenities.map(([Icon,title,desc]:any)=><article className="amenity" key={title}><Icon size={24}/><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="center-action"><Link className="btn btn-gold" href="/tien-ich">Khám phá tiện ích</Link></div></div></section>
<section className="cta"><div className="shell"><span className="eyebrow">Tư vấn riêng</span><h2>Để chúng tôi đồng hành cùng gia đình</h2><p>Nhận thông tin chi tiết và đăng ký lịch tham quan Cao Thanh Tâm.</p><div className="actions justify-center"><Link className="btn btn-gold" href="/lien-he">Đăng ký tư vấn <ArrowRight size={15}/></Link></div></div></section>
</main>}
