"use client";

import { useEffect, useMemo, useState } from "react";
import { FileText, Home, Images, LayoutDashboard, Plus, Save, ShieldCheck, Trash2, Users } from "lucide-react";

type Tab = "dashboard"|"home"|"albums"|"posts"|"staff";
type Album = {id:number;title:string;cover:string;count:number};
type Post = {id:number;title:string;status:"Nháp"|"Đã xuất bản";date:string};
type Staff = {id:number;name:string;email:string;role:"Quản trị viên"|"Biên tập viên"|"Nhân viên nội dung";active:boolean};

type HomeData = {heroTitle:string;heroSubtitle:string;heroDescription:string;hotline:string};

const homeDefault:HomeData={heroTitle:"THIÊN PHÚC VĨNH HẰNG VIÊN",heroSubtitle:"THANH TỊNH – NHÂN VĂN – TRƯỜNG TỒN",heroDescription:"Công viên nghĩa trang sinh thái cao cấp tại Uông Bí – Yên Tử, nơi giao hòa giữa thiên nhiên và tâm linh.",hotline:"0976074385"};
const albumDefault:Album[]=[{id:1,title:"Toàn cảnh dự án",cover:"",count:8},{id:2,title:"Tiến độ thi công",cover:"",count:12}];
const postDefault:Post[]=[{id:1,title:"Khởi động dự án Công viên nghĩa trang Thiên Phúc Vĩnh Hằng Viên",status:"Đã xuất bản",date:"02/06/2026"},{id:2,title:"Không gian an nghỉ sinh thái tại Yên Tử",status:"Nháp",date:"20/05/2026"}];
const staffDefault:Staff[]=[{id:1,name:"Quản trị hệ thống",email:"admin@thienphuc.vn",role:"Quản trị viên",active:true}];

function useLocalState<T>(key:string,initial:T){const[state,setState]=useState(initial);useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw)setState(JSON.parse(raw))}catch{}},[key]);const save=(value:T)=>{setState(value);try{localStorage.setItem(key,JSON.stringify(value))}catch{}};return[state,save] as const}

export default function AdminConsole(){
 const[tab,setTab]=useState<Tab>("dashboard");
 const[home,setHome]=useLocalState("tp-admin-home",homeDefault);
 const[albums,setAlbums]=useLocalState("tp-admin-albums",albumDefault);
 const[posts,setPosts]=useLocalState("tp-admin-posts",postDefault);
 const[staff,setStaff]=useLocalState("tp-admin-staff",staffDefault);
 const[notice,setNotice]=useState("");
 const stats=useMemo(()=>[{label:"Bài viết",value:posts.length,icon:FileText},{label:"Album ảnh",value:albums.length,icon:Images},{label:"Nhân viên",value:staff.length,icon:Users},{label:"Đang hoạt động",value:staff.filter(x=>x.active).length,icon:ShieldCheck}],[posts,albums,staff]);
 const saved=(msg:string)=>{setNotice(msg);setTimeout(()=>setNotice(""),2200)};
 return <main className="admin-shell">
  <aside className="admin-sidebar"><div className="admin-logo"><b>THIÊN PHÚC</b><span>ADMIN CMS</span></div><nav>{[["dashboard",LayoutDashboard,"Tổng quan"],["home",Home,"Sửa trang chủ"],["albums",Images,"Album ảnh"],["posts",FileText,"Bài viết"],["staff",Users,"Nhân viên & phân quyền"]].map(([id,Icon,label]:any)=><button key={id} onClick={()=>setTab(id)} className={tab===id?"active":""}><Icon size={18}/>{label}</button>)}</nav><div className="admin-sidebar-foot"><span>Phiên bản quản trị 1.0</span><a href="/">← Xem website</a></div></aside>
  <section className="admin-main"><header className="admin-topbar"><div><small>HỆ THỐNG QUẢN TRỊ</small><h1>{tab==="dashboard"?"Tổng quan":tab==="home"?"Sửa trang chủ":tab==="albums"?"Quản lý album ảnh":tab==="posts"?"Quản lý bài viết":"Nhân viên & phân quyền"}</h1></div><div className="admin-user"><span>Quản trị viên</span><b>AD</b></div></header>
  {notice&&<div className="admin-notice">{notice}</div>}
  <div className="admin-local-warning">Hiện dữ liệu quản trị đang lưu cục bộ trên trình duyệt để hoàn thiện giao diện CMS. Cần kết nối cơ sở dữ liệu và đăng nhập thật trước khi dùng cho nhiều nhân viên.</div>
  {tab==="dashboard"&&<><div className="admin-stats">{stats.map(({label,value,icon:Icon})=><article key={label}><Icon size={21}/><div><b>{value}</b><span>{label}</span></div></article>)}</div><div className="admin-panels"><article><h2>Truy cập nhanh</h2><div className="quick-grid"><button onClick={()=>setTab("home")}><Home/>Sửa nội dung trang chủ</button><button onClick={()=>setTab("albums")}><Images/>Thêm album ảnh</button><button onClick={()=>setTab("posts")}><FileText/>Viết bài mới</button><button onClick={()=>setTab("staff")}><Users/>Phân quyền nhân viên</button></div></article><article><h2>Tình trạng hệ thống</h2><ul className="status-list"><li><span/>Website đang hoạt động</li><li><span/>Vercel tự động triển khai</li><li><span className="warn"/>CSDL quản trị chưa kết nối</li></ul></article></div></>}
  {tab==="home"&&<div className="admin-card"><div className="admin-card-head"><div><h2>Nội dung Hero trang chủ</h2><p>Chỉnh nội dung chính hiển thị ở đầu website.</p></div><button className="admin-primary" onClick={()=>{setHome({...home});saved("Đã lưu nội dung trang chủ")}}><Save size={16}/>Lưu thay đổi</button></div><div className="admin-form"><label>Tiêu đề chính<input value={home.heroTitle} onChange={e=>setHome({...home,heroTitle:e.target.value})}/></label><label>Thông điệp nổi bật<input value={home.heroSubtitle} onChange={e=>setHome({...home,heroSubtitle:e.target.value})}/></label><label>Mô tả<textarea rows={4} value={home.heroDescription} onChange={e=>setHome({...home,heroDescription:e.target.value})}/></label><label>Hotline<input value={home.hotline} onChange={e=>setHome({...home,hotline:e.target.value})}/></label></div></div>}
  {tab==="albums"&&<div className="admin-card"><div className="admin-card-head"><div><h2>Album hình ảnh</h2><p>Tạo album để phân loại hình ảnh dự án.</p></div><button className="admin-primary" onClick={()=>{const title=prompt("Tên album mới");if(title){setAlbums([...albums,{id:Date.now(),title,cover:"",count:0}]);saved("Đã tạo album mới")}}}><Plus size={16}/>Thêm album</button></div><div className="admin-table">{albums.map(a=><div className="admin-row" key={a.id}><div className="album-thumb"><Images size={22}/></div><div className="grow"><b>{a.title}</b><span>{a.count} hình ảnh</span></div><button className="icon-btn" onClick={()=>{setAlbums(albums.filter(x=>x.id!==a.id));saved("Đã xóa album")}}><Trash2 size={17}/></button></div>)}</div></div>}
  {tab==="posts"&&<div className="admin-card"><div className="admin-card-head"><div><h2>Bài viết & tin tức</h2><p>Tạo, lưu nháp và quản lý nội dung tin tức.</p></div><button className="admin-primary" onClick={()=>{const title=prompt("Tiêu đề bài viết");if(title){setPosts([{id:Date.now(),title,status:"Nháp",date:new Date().toLocaleDateString("vi-VN")},...posts]);saved("Đã tạo bài viết nháp")}}}><Plus size={16}/>Viết bài mới</button></div><div className="admin-table">{posts.map(p=><div className="admin-row" key={p.id}><div className="post-icon"><FileText size={19}/></div><div className="grow"><b>{p.title}</b><span>{p.date}</span></div><select value={p.status} onChange={e=>setPosts(posts.map(x=>x.id===p.id?{...x,status:e.target.value as Post["status"]}:x))}><option>Nháp</option><option>Đã xuất bản</option></select><button className="icon-btn" onClick={()=>setPosts(posts.filter(x=>x.id!==p.id))}><Trash2 size={17}/></button></div>)}</div></div>}
  {tab==="staff"&&<div className="admin-card"><div className="admin-card-head"><div><h2>Nhân viên & phân quyền</h2><p>Quản lý vai trò cho từng người dùng hệ thống.</p></div><button className="admin-primary" onClick={()=>{const name=prompt("Tên nhân viên");const email=name?prompt("Email nhân viên"):null;if(name&&email){setStaff([...staff,{id:Date.now(),name,email,role:"Nhân viên nội dung",active:true}]);saved("Đã thêm nhân viên")}}}><Plus size={16}/>Thêm nhân viên</button></div><div className="admin-table">{staff.map(s=><div className="admin-row staff-row" key={s.id}><div className="staff-avatar">{s.name.slice(0,2).toUpperCase()}</div><div className="grow"><b>{s.name}</b><span>{s.email}</span></div><select value={s.role} onChange={e=>setStaff(staff.map(x=>x.id===s.id?{...x,role:e.target.value as Staff["role"]}:x))}><option>Quản trị viên</option><option>Biên tập viên</option><option>Nhân viên nội dung</option></select><label className="switch-label"><input type="checkbox" checked={s.active} onChange={e=>setStaff(staff.map(x=>x.id===s.id?{...x,active:e.target.checked}:x))}/><span>{s.active?"Hoạt động":"Khóa"}</span></label>{s.id!==1&&<button className="icon-btn" onClick={()=>setStaff(staff.filter(x=>x.id!==s.id))}><Trash2 size={17}/></button>}</div>)}</div><div className="role-help"><h3>Quyền mặc định</h3><p><b>Quản trị viên:</b> toàn quyền hệ thống. <b>Biên tập viên:</b> quản lý bài viết, album và nội dung trang. <b>Nhân viên nội dung:</b> tạo/sửa nội dung nhưng không quản lý nhân viên.</p></div></div>}
  </section>
 </main>
}
