"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {FileText,Home,Images,LayoutDashboard,Plus,Save,Upload,Users} from "lucide-react";
type Tab="dashboard"|"home"|"albums"|"posts"|"staff";type Photo={id:string;url:string;name:string;albumId:string;createdAt:string};type Album={id:string;title:string;createdAt:string};type Post={id:string;title:string;status:"Nháp"|"Đã xuất bản";date:string};type Staff={id:string;name:string;email:string;role:string;active:boolean};type CmsData={home:{heroTitle:string;heroSubtitle:string;heroDescription:string;hotline:string};albums:Album[];photos:Photo[];posts:Post[];staff:Staff[]};
const empty:CmsData={home:{heroTitle:"",heroSubtitle:"",heroDescription:"",hotline:""},albums:[],photos:[],posts:[],staff:[]};
export default function AdminConsole(){const[tab,setTab]=useState<Tab>("dashboard"),[data,setData]=useState<CmsData>(empty),[ready,setReady]=useState(false),[error,setError]=useState(""),[storage,setStorage]=useState(false),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[selectedAlbum,setSelectedAlbum]=useState("");const fileRef=useRef<HTMLInputElement>(null);
async function load(){setError("");try{const r=await fetch("/api/cms",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(!j?.data)throw new Error("CMS không trả dữ liệu");setData(j.data);setStorage(!!j.storage);setSelectedAlbum(v=>j.data.albums.some((a:Album)=>a.id===v)?v:j.data.albums?.[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Không thể tải CMS")}finally{setReady(true)}}useEffect(()=>{load()},[]);
const stats=useMemo(()=>[["Bài viết",data.posts.length,FileText],["Album ảnh",data.albums.length,Images],["Hình ảnh",data.photos.length,Upload],["Nhân viên",data.staff.length,Users]] as const,[data]);const photos=data.photos.filter(p=>p.albumId===selectedAlbum);const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),5000)};
async function save(next=data,msg="Đã lưu thay đổi"){setSaving(true);try{const r=await fetch("/api/cms",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});const j=await r.json();if(!r.ok)throw new Error(j.error||String(r.status));setData(j.data||next);flash(msg);return true}catch(e){flash(`Không thể lưu: ${e instanceof Error?e.message:"Lỗi"}`);return false}finally{setSaving(false)}}
async function upload(files:FileList|null){if(!files?.length||!selectedAlbum)return;setUploading(true);let ok=0;for(const file of Array.from(files)){try{const form=new FormData();form.append("albumId",selectedAlbum);form.append("file",file);const r=await fetch("/api/cms/upload",{method:"POST",body:form});if(r.ok)ok++}catch{}}await load();setUploading(false);if(fileRef.current)fileRef.current.value="";flash(`Đã tải ${ok}/${files.length} ảnh`)}
if(!ready)return <main className="admin-shell"><section className="admin-main"><div className="admin-card"><h2>Đang tải hệ thống quản trị...</h2></div></section></main>;if(error)return <main className="admin-shell"><section className="admin-main"><div className="admin-card"><h2>Không tải được CMS</h2><p>{error}</p><button className="admin-primary" onClick={()=>{setReady(false);load()}}>Thử tải lại</button></div></section></main>;
return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><b>THIÊN PHÚC</b><span>ADMIN CMS</span></div><nav>{[["dashboard",LayoutDashboard,"Tổng quan"],["home",Home,"Sửa trang chủ"],["albums",Images,"Album ảnh"],["posts",FileText,"Bài viết"],["staff",Users,"Nhân viên"]].map(([id,Icon,label]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><div className="admin-sidebar-foot"><a href="/">← Xem website</a></div></aside><section className="admin-main"><header className="admin-topbar"><div><small>HỆ THỐNG QUẢN TRỊ</small><h1>{tab==="dashboard"?"Tổng quan":tab==="home"?"Sửa trang chủ":tab==="albums"?"Quản lý album ảnh":tab==="posts"?"Bài viết":"Nhân viên"}</h1></div></header>{notice&&<div className="admin-notice">{notice}</div>}<div className={storage?"admin-storage-ok":"admin-local-warning"}>{storage?"Vercel Blob đã kết nối. Dữ liệu admin và website đang đồng bộ.":"Vercel Blob chưa kết nối."}</div>
{tab==="dashboard"&&<div className="admin-stats">{stats.map(([label,value,Icon])=><article key={label}><Icon size={21}/><div><b>{value}</b><span>{label}</span></div></article>)}</div>}
{tab==="home"&&<div className="admin-card"><div className="admin-card-head"><h2>Nội dung trang chủ</h2><button className="admin-primary" disabled={saving} onClick={()=>save()}><Save size={16}/>{saving?"Đang lưu...":"Lưu thay đổi"}</button></div><div className="admin-form"><label>Tiêu đề<input value={data.home.heroTitle} onChange={e=>setData({...data,home:{...data.home,heroTitle:e.target.value}})}/></label><label>Thông điệp<input value={data.home.heroSubtitle} onChange={e=>setData({...data,home:{...data.home,heroSubtitle:e.target.value}})}/></label><label>Mô tả<textarea rows={4} value={data.home.heroDescription} onChange={e=>setData({...data,home:{...data.home,heroDescription:e.target.value}})}/></label><label>Hotline<input value={data.home.hotline} onChange={e=>setData({...data,home:{...data.home,hotline:e.target.value}})}/></label></div></div>}
{tab==="albums"&&<div className="admin-card"><div className="admin-card-head"><div><h2>Album hình ảnh</h2><p>Chọn album và tải ảnh trực tiếp lên kho ảnh website.</p></div><button className="admin-primary" onClick={async()=>{const title=prompt("Tên album mới");if(title)await save({...data,albums:[...data.albums,{id:`album-${Date.now()}`,title,createdAt:new Date().toISOString()}]},"Đã tạo album")}}><Plus size={16}/>Thêm album</button></div><div className="admin-upload-box"><select value={selectedAlbum} onChange={e=>setSelectedAlbum(e.target.value)}>{data.albums.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><input ref={fileRef} hidden type="file" accept="image/*,.heic,.heif" multiple onChange={e=>upload(e.target.files)}/><button className="admin-primary" disabled={!storage||uploading||!selectedAlbum} onClick={()=>fileRef.current?.click()}><Upload size={16}/>{uploading?"Đang tải...":"Chọn nhiều ảnh"}</button></div><div className="admin-album-grid">{data.albums.map(a=>{const ps=data.photos.filter(p=>p.albumId===a.id);return <article key={a.id} className={selectedAlbum===a.id?"selected":""} onClick={()=>setSelectedAlbum(a.id)}><div className="admin-album-cover">{ps[0]?<img src={ps[0].url} alt={a.title}/>:<Images/>}</div><div><b>{a.title}</b><span>{ps.length} hình ảnh</span></div></article>})}</div><h3 className="admin-gallery-title">Ảnh trong album</h3><div className="admin-photo-grid">{photos.map(p=><figure key={p.id}><img src={p.url} alt={p.name}/><figcaption>{p.name}</figcaption></figure>)}</div></div>}
{tab==="posts"&&<div className="admin-card"><h2>Bài viết</h2>{data.posts.map(p=><p key={p.id}><b>{p.title}</b> — {p.status}</p>)}</div>}{tab==="staff"&&<div className="admin-card"><h2>Nhân viên</h2>{data.staff.map(s=><p key={s.id}><b>{s.name}</b> — {s.role}</p>)}</div>}</section></main>}
