import type { Metadata } from "next";
import Image from "next/image";
import InnerHero from "@/components/InnerHero";
import { getCmsData } from "@/lib/cms";

export const dynamic="force-dynamic";
export const metadata: Metadata={title:"Quy hoạch",description:"Thông tin quy hoạch và mặt bằng tổng thể Thiên Phúc Vĩnh Hằng Viên."};
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase();
export default async function PlanningPage(){const cms=await getCmsData();const album=cms.albums.find(a=>norm(a.title).includes("mat bang tong the"));const photos=album?cms.photos.filter(p=>p.albumId===album.id):[];return <main><InnerHero eyebrow="Mặt bằng tổng thể" title="Quy hoạch dự án" description="Thiên Phúc Vĩnh Hằng Viên được định hướng như một công viên nghĩa trang sinh thái đồng bộ giữa cảnh quan, công trình tâm linh, hạ tầng và các khu an táng."/><section className="section"><div className="shell two"><div><span className="eyebrow">Định hướng quy hoạch</span><h2 className="section-title">32,54 ha được tổ chức thành một tổng thể hài hòa</h2><p className="lead">Quy hoạch dự án chú trọng sự cân bằng giữa không gian an táng, mảng xanh, đường giao thông nội khu, công trình nghi lễ và các khu dịch vụ phục vụ gia đình.</p><p className="lead">Các phân khu được kết nối bằng hệ thống cảnh quan thống nhất, hướng tới trải nghiệm trang nghiêm, thuận tiện và bền vững trong suốt quá trình thăm viếng.</p></div><div className="quote-panel"><p>Quy mô dự án: 32,54 ha<br/>Tổng mức đầu tư: khoảng 451 tỷ đồng<br/>Dự kiến hoàn thành: Quý II/2028</p></div></div></section>{photos[0]&&<section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Hình ảnh quy hoạch</span><h2 className="section-title">Mặt bằng tổng thể dự án</h2></div><div style={{position:"relative",width:"100%",aspectRatio:"16/8",borderRadius:18,overflow:"hidden"}}><Image src={photos[0].url} alt="Mặt bằng tổng thể Thiên Phúc Vĩnh Hằng Viên" fill sizes="100vw" quality={72} style={{objectFit:"cover"}}/></div></div></section>}</main>}
